### PR TITLE
DefaultEntityRepository cleanup

### LINKED ISSUE #502: Refactor AttachRelationships: prevent reattachment, support implicit remove
### Problem
Consider the following scenario 
* `Person` one-to-one `Passport`
* initial condition of the database:  
     * two `Person`s items: `person1, person2`.
     * only one `Passport` item: `passport`
     * foreign key `PassportId` on `person1` equals id of `passport`

We now do a `PATCH /people/2` and attempt to update the relationship of  `person2` by relating it to `passport`. What I would expect it to do is to perform an **implicit remove** of the old relationship: implicit in the sense that the relationship with `person1` is updated even though it was never explicitly mentioned in the original request.

Right now, it results in a 500 because a foreign key constraint is violated. This is because `person1` is already related to `passport` and the implicit remove is not taken care of, resulting in a FK constraint error.

[Update bug reproduced in this test](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/926a94594559e0963b313be18d39e6c7bcf0c859/test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/UpdatingRelationshipsTests.cs#L626)

Issue: a 500 is not acceptable.

### Solution

Two options
1) Don't actually do the implicit remove, but return a `400 Bad Request` with a body stating that the relation between `person1` and `passport` should be removed first, thus more or less reflecting the foreign key constraint error message that is generated by the database~
2) handle these situations intelligently in the repository layer. The repository layer would take care of breaking the relationship between `person1` and `passport`  before relating `person2` to `passport`. EF Core can handle this trivially if we just attach `person1` to the `dbContext` before saving the changes (by just loading the Person relationship of passport). Right now that doesn't happen.

I prefer the second option.

**[EDIT]**

This goes wrong for `CREATE`, `UPDATE` for both one-to-one and one-to-many. All goes in a similar way: the entity on the inverse navigation property needs to be attached. This means that the fix is not specific to one particular "pipeline", but the `AttachRelationship` method which is called in all involved pipelines needs an upgrade:
* for `many-to-many` and `one-to-many`: needs to attach relationships of the to-be-manipulated entity so that complete replacement actually works (see #492  and #494)
* for `one-to-one` and `one-to-many`: It needs to do attachment of inverse relationships to prevent the error as mentioned above from occurring. See #503: it has a proof of concept for the specific example above
* needs to take care we're never re-attaching entities that were loaded into `dbContext` elsewhere in the application, see `DefaultEntityRepository.PreventReattachment (private method)` in #494.
* Needs to be refactored such that `AttachRelationships` is consistent with respect to assigning the actual new relationship values. In the current implementation, for `one-to-many` and `one-to-one` they are not assigned in this method, but for `many-to-many` they are. This is inconsistent, which makes it a lot harder to prevent reattachment in a simple way.

### LINKED ISSUE #520: Bad PATCH request (without ID) does not return HTTP 400
There are currently several PATCH related tests (for example [Can_Patch_CamelCasedModels](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/8b630c471d7973fa6621ed6f978bc866a6d95a7c/test/JsonApiDotNetCoreExampleTests/Acceptance/CamelCasedModelsControllerTests.cs#L133)) that are passing but shouldn't. When [according to the specs](https://jsonapi.org/format/#crud-updating), the id attribute must be included in the request body

> The PATCH request MUST include a single resource object as primary data. The resource object MUST contain type and id members.

Therefore any PATCH request without ID should return a http 400.

### PR DESCRIPTION
**Pull request by maurei**
This PR fixes of several issues and a bunch of refactoring.

* fixes an issue with EF Core exceptions thrown when `DefaultEntityRepository` tries to attach entities to the `DbContext` that are already attached. This may happened when entities involved to a update or create request were already loaded in the dbcontext elsewhere (eg Resource Hooks). Closes #502. This fix is needed for the tests to pass in #478  
     * added consistent handling for tracked entities
* support for implicit removal of relationships. For this the `IInverseRelationship` service is introduced (actually it was cherry picked from the Resource Hooks PR).  See #502.
* Refactored the `AttachRelationships` method and those associated to it such that
     * it doesn't also *assign* relationshipvalues in (only) the case of many-to-many
     * it no longer depends on `IJsonApiContext` for the *values* of updated relationships and attributes. Still uses it to identify *which* attributes/relationships to update. See #519
* Marked `UpdateAsync(TId id, TEnity entity)` as obsolete, added a new one: `UpdateAsync(TEnity updatedEntity)` which actually uses the updated entity in the repository layer, as opposed to it just being passed along and being left untouched in the previous implementation.  See #519 
* Refactored the fix that was included earlier to support complete replace for PATCH requests (see #492 and #494).
* Refactored the usage of the following properties of `IJsonApiContex` `RelationshipsToUpdate`, `HasOnePointers`, `HasManyPointers`. The first one has become an alias for the latter two, and the latter two are no longer populated with the actual relationship  values as these are not used anymore in the repository layer. This is related to #512.
* No longer allowing PATCH requests that do not contain ID values in the request body. Fixes #520

### CODE REVIEW

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs [hunk 1]
```diff
@@ -147,217 +144,186 @@ public virtual async Task<TEntity> GetAndIncludeAsync(TId id, string relationshi
...
-        public virtual async Task<TEntity> UpdateAsync(TId id, TEntity entity)
+        [Obsolete("Use overload UpdateAsync(TEntity updatedEntity): providing parameter ID does no longer add anything relevant")]
+        public virtual async Task<TEntity> UpdateAsync(TId id, TEntity updatedEntity)
         {
-            var oldEntity = await GetAsync(id);
+            return await UpdateAsync(updatedEntity);
+        }
 
+        /// <inheritdoc />
+        public virtual async Task<TEntity> UpdateAsync(TEntity updatedEntity)
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: So, I get what's happening here, but can you use an example to signify what's happening here? The technical documentation is great, but a solid example for easy reading is great for when you haven't had your coffee yet.

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs [hunk 2]
```diff
@@ -470,5 +432,119 @@ public async Task<IReadOnlyList<TEntity>> ToListAsync(IQueryable<TEntity> entiti
...
         }
+
+
+        /// <summary>
+        /// Before assigning new relationship values (UpdateAsync), we need to
+        /// attach the current relationship state to the dbcontext, else 
+        /// it will not perform a complete-replace which is required for 
+        /// one-to-many and many-to-many.
+        /// </summary>
+        protected void LoadCurrentRelationships(TEntity oldEntity, RelationshipAttribute relationshipAttribute)
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: So here I would make it apparent that we're fetching actual database values

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs [hunk 3]
```diff
@@ -147,217 +144,186 @@ public virtual async Task<TEntity> GetAndIncludeAsync(TId id, string relationshi
...
-                        relationship.Key.SetValue(oldEntity, relationship.Value);
-                    }
-                    if ((relationship.Key.TypeId as Type).IsAssignableFrom(typeof(HasManyAttribute)))
-                    {
-                        await _context.Entry(oldEntity).Collection(relationship.Key.InternalRelationshipName).LoadAsync();
-                        var value = PreventReattachment((IEnumerable<object>)relationship.Value);
-                        relationship.Key.SetValue(oldEntity, value);
-                    }
-                }
+                LoadCurrentRelationships(oldEntity, relationshipAttr);
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: Could you refactor this into one class?

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs [hunk 4]
```diff
@@ -470,5 +432,119 @@ public async Task<IReadOnlyList<TEntity>> ToListAsync(IQueryable<TEntity> entiti
...
+            }
+        }
+
+        /// <summary>
+        /// assigns relationships that were set in the request to the target entity of the request
+        /// todo: partially remove dependency on IJsonApiContext here: it is fine to
+        /// retrieve from the context WHICH relationships to update, but the actual
+        /// values should not come from the context.
+        /// </summary>
+        private void AssignRelationshipValue(TEntity oldEntity, object relationshipValue, RelationshipAttribute relationshipAttribute)
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: Dont leave todos in summaries

File: src/JsonApiDotNetCore/Extensions/TypeExtensions.cs [hunk 5]
```diff
@@ -8,6 +8,13 @@ namespace JsonApiDotNetCore.Extensions
 {
     internal static class TypeExtensions
     {
+        public static IEnumerable Cast(this IEnumerable source, Type type)
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Extensions/TypeExtensions.cs]: comment

File: src/JsonApiDotNetCore/Formatters/JsonApiReader.cs [hunk 6]
```diff
@@ -62,6 +83,38 @@ public Task<InputFormatterResult> ReadAsync(InputFormatterContext context)
             }
         }
 
+        private bool CheckForId(object model)
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Formatters/JsonApiReader.cs]: comment

File: src/JsonApiDotNetCore/Formatters/JsonApiReader.cs [hunk 7]
```diff
@@ -62,6 +83,38 @@ public Task<InputFormatterResult> ReadAsync(InputFormatterContext context)
...
+                if (string.IsNullOrEmpty(ro.Id)) return true;
+            }
+            else if (model is IIdentifiable identifiable)
+            {
+                if (string.IsNullOrEmpty(identifiable.StringId)) return true;
+            }
+            return false;
+        }
+
+        private bool CheckForId(IList modelList)
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Formatters/JsonApiReader.cs]: comment

File: src/JsonApiDotNetCore/Internal/InverseRelationships.cs [hunk 8]
```diff
@@ -0,0 +1,65 @@
...
+    /// This service is instantiated in the configure phase of the application.
+    /// 
+    /// When using a data access layer different from EF Core, and when using ResourceHooks
+    /// that depend on the inverse navigation property (BeforeImplicitUpdateRelationship),
+    /// you will need to override this service, or pass along the inverseNavigationProperty in
+    /// the RelationshipAttribute.
+    /// </summary>
+    public interface IInverseRelationships
+    {
+        void Resolve();
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Internal/InverseRelationships.cs]: comment

File: src/JsonApiDotNetCore/Internal/InverseRelationships.cs [hunk 9]
```diff
@@ -0,0 +1,65 @@
...
+        private readonly ResourceGraph _graph;
+        private readonly IDbContextResolver _resolver;
+
+        public InverseRelationships(IResourceGraph graph, IDbContextResolver resolver = null)
+        {
+            _graph = (ResourceGraph)graph;
+            _resolver = resolver;
+        }
+
+        public void Resolve()
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Internal/InverseRelationships.cs]: inherit

File: src/JsonApiDotNetCore/Models/RelationshipAttribute.cs [hunk 10]
```diff
@@ -15,8 +15,10 @@ protected RelationshipAttribute(string publicName, Link documentLinks, bool canI
         }
 
         public string PublicRelationshipName { get; internal set; }
-        public string InternalRelationshipName { get; internal set; } 
-        
+        public string InternalRelationshipName { get; internal set; }
+
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Models/RelationshipAttribute.cs]: empty space?

File: src/JsonApiDotNetCore/Serialization/JsonApiDeSerializer.cs [hunk 11]
```diff
@@ -155,7 +155,11 @@ public object DocumentToObject(ResourceObject data, List<ResourceObject> include
                         continue;
                     var convertedValue = ConvertAttrValue(newValue, attr.PropertyInfo.PropertyType);
                     attr.SetValue(entity, convertedValue);
-                    _jsonApiContext.AttributesToUpdate[attr] = convertedValue;
+                    /// todo: as a part of the process of decoupling JADNC (specifically
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Serialization/JsonApiDeSerializer.cs]: add a reference or something like: #512  reference

File: src/JsonApiDotNetCore/Services/EntityResourceService.cs [hunk 12]
```diff
@@ -154,7 +154,7 @@ public virtual async Task<TResource> UpdateAsync(TId id, TResource resource)
         {
             var entity = MapIn(resource);
 
-            entity = await _entities.UpdateAsync(id, entity);
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Services/EntityResourceService.cs]: why not immediatly into mapout?

File: test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/UpdatingDataTests.cs [hunk 13]
```diff
@@ -55,8 +55,9 @@ public async Task Response400IfUpdatingNotSettableAttribute()
 
             var content = new
             {
-                datea = new
```
Comment (wisepotato) [inline test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/UpdatingDataTests.cs]: nice.

File: src/JsonApiDotNetCore/Extensions/TypeExtensions.cs (hunk 5 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Extensions/TypeExtensions.cs]: fixed in c34d22ac1af94c50d735e09d1d99759200cd0d6f

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs (hunk 4 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: fixed in bf520a06ba81bb0df9e08a0ec43fdd83982b78b2

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs (hunk 3 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: Yes: it would be nice to have a helper class to make it all more readable. But leaving this as a stretch goal for the future. This shouldn't be a problem as it won't introduce any breaking changes, so we can refactor this whenever we like.

File: src/JsonApiDotNetCore/Models/RelationshipAttribute.cs (hunk 10 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Models/RelationshipAttribute.cs]: Diff seems to be misleading, empty space is not actually there

File: src/JsonApiDotNetCore/Services/EntityResourceService.cs (hunk 12 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Services/EntityResourceService.cs]: Easy to fix; but limiting this PR to upgrading the repository

File: src/JsonApiDotNetCore/Internal/InverseRelationships.cs (hunk 9 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Internal/InverseRelationships.cs]: fixed in 457e93dbb38784220565d687c799acadf82350d1

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs (hunk 2 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: fixed in 457e93dbb38784220565d687c799acadf82350d1

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs (hunk 1 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: fixed in 457e93dbb38784220565d687c799acadf82350d1

File: src/JsonApiDotNetCore/Serialization/JsonApiDeSerializer.cs (hunk 11 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Serialization/JsonApiDeSerializer.cs]: fixed in 457e93dbb38784220565d687c799acadf82350d1

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs [hunk 14]
```diff
@@ -62,7 +62,8 @@ public class DefaultEntityRepository<TEntity, TId>
             _resourceDefinition = resourceDefinition;
         }
 
-        public DefaultEntityRepository(
+        public
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: what?

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs [hunk 15]
```diff
@@ -171,6 +172,13 @@ public virtual async Task<TEntity> CreateAsync(TEntity entity)
         /// <summary>
         /// Loads the inverse relationships to prevent foreign key constraints from being violated
         /// to support implicit removes, see https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/502.
+        /// 
+        /// example:
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: add in <example> tag

File: src/JsonApiDotNetCore/Extensions/TypeExtensions.cs [hunk 16]
```diff
@@ -8,6 +8,32 @@ namespace JsonApiDotNetCore.Extensions
 {
     internal static class TypeExtensions
     {
+        public static void AddRange<T>(this IList list, IEnumerable<T> items)
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Extensions/TypeExtensions.cs]: Comment

Comment (maurei) [reply src/JsonApiDotNetCore/Extensions/TypeExtensions.cs]: This code wasn't added in this PR, don't know why the diff shows it as such

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs (hunk 15 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: The explanation that follows isn't something that in the documentation should be generated as a code example. Edited it to be more readable.

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs [hunk 17]
```diff
@@ -172,8 +171,8 @@ public virtual async Task<TEntity> CreateAsync(TEntity entity)
         /// <summary>
         /// Loads the inverse relationships to prevent foreign key constraints from being violated
         /// to support implicit removes, see https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/502.
-        /// 
-        /// example: 
+        /// <para/>
```
Comment (wisepotato) [inline src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: para? `<example>`
