### PR TITLE
fix(#343): reload relationships from database if included during POST

### LINKED ISSUE #343: [2.4.0-beta1]: POST with self referencing inclusion returns null values (or default) in included entity
I have entity Client like this:

```
public class Client : Identifiable
    {
        [Attr("firstName")]
        public string FirstName  { get; set; }

        [Attr("lastName")]
        public string LastName  { get; set; }

        //[HasOne("advisor", Link.None)]
        //public Advisor Advisor { get; set; }
        //public int AdvisorId { get; set; }

        [HasOne("recommender", Link.None)]
        public Client Recommender { get; set; }
        public int? RecommenderId { get; set; }
    }

```
Trying to post like:
POST: http://localhost:5001/api/clients?include=recommender

```
{  
   "data":{  
      "type":"clients",
      "attributes":{  
         "firstName":"Mike",
         "lastName":"Razor"
      },
      "relationships":{  
         "recommender":{  
            "data":{  
               "type":"clients",
               "id":"1"
            }
         }
      }
   }
}
```

It returns:

```
{  
   "data":{  
      "attributes":{  
         "firstName":"Mike",
         "lastName":"Razor"
      },
      "relationships":{  
         "recommender":{  
            "data":{  
               "type":"clients",
               "id":"1"
            }
         }
      },
      "type":"clients",
      "id":"2"
   },
   "included":[  
      {  
         "attributes":{  
            "firstName":null,  // <--- This should be not null
            "lastName":null   // <--- This should be not null
         },
         "relationships":{  
            "recommender":{}
         },
         "type":"clients",
         "id":"1"
      }
   ]
}
```
This is caused only when there is self referencing inclusion (client include another client).
When I change POST with entity of another type (commented Advisor for example), POST with inclusion returns all data normally.

In version 2.3.1 it works fine. 2.3.2 and above has this problem

### PR DESCRIPTION
**Pull request by jaredcnance**
Closes #343

#### BUG FIX
- [x] reproduce issue in tests
- [x] fix issue
- [x] bump package version

Verified solution results in only two queries regardless of number of included relationships:

image

### CODE REVIEW

File: src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs [hunk 1]
```diff
@@ -185,10 +193,57 @@ public virtual IQueryable<TEntity> Include(IQueryable<TEntity> entities, string
...
+            if (relationshipAttr.IsHasOne && _jsonApiContext.HasOneRelationshipPointers.Get().TryGetValue(relationshipAttr, out var pointer))
+            {
+                await _context.Entry(pointer).ReloadAsync();
+            }
+
+            if (relationshipAttr.IsHasMany && _jsonApiContext.HasManyRelationshipPointers.Get().TryGetValue(relationshipAttr, out var pointers))
+            {
+                foreach (var hasManyPointer in pointers)
+                {
+                    await _context.Entry(hasManyPointer).ReloadAsync();
```
Comment (jaredcnance) [inline src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: this is bad ☹️  ... need to reload the entire navigation property

Comment (milosloub) [reply src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: First of all. Thank you, for this solution.
For HasMany relationships, what about something like:
_context.Entry(entity).Collection(relation).Load();

instead of:
foreach (var pointer in hasManyRelationship.Value)
{
       _context.Entry(pointer).State = EntityState.Detached;
}

Comment (jaredcnance) [reply src/JsonApiDotNetCore/Data/DefaultEntityRepository.cs]: Thanks for the suggestion, I wasn't aware of the `.Collection` api. I _think_ I like the approach I ended up taking better. The reason is that we should end up with a single SQL request that uses `JOIN` to load all the relationships rather than reloading each included relationship individually. I'll review it again later tonight to verify the difference.
