### PR TITLE
Fix: incorrect resource type comparison

### LINKED ISSUE #789: Type match incorrect for PATCH requests
It seems logic is at fault at:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/36bc4896a4072b0fe330fe69e65aed78ec6f573c/src/JsonApiDotNetCore/Middleware/DefaultTypeMatchFilter.cs#L33-L34

For PATCH requests that will compare the path id parameter not the entity.

### PR DESCRIPTION
**Pull request by maurei**
Fixes #789 

- No longer relies on `ActionDescriptor` to get an expected type, but retrieves it from `IJsonApiRequest` instead

### CODE REVIEW

**Comment by bart-degreed** [comment]
@maurei Can you resolve merge conflicts?

File: src/JsonApiDotNetCore/Serialization/JsonApiReader.cs [hunk 1]
```diff
@@ -16,17 +21,20 @@ namespace JsonApiDotNetCore.Serialization
...
+            IJsonApiRequest jsonApiRequest,
+            IResourceContextProvider resourceContextProvider,
             ILoggerFactory loggerFactory)
         {
             if (loggerFactory == null) throw new ArgumentNullException(nameof(loggerFactory));
 
             _deserializer = deserializer ?? throw new ArgumentNullException(nameof(deserializer));
-            _request = request ?? throw new ArgumentNullException(nameof(request));
+            _jsonApiRequest = jsonApiRequest ?? throw new ArgumentNullException(nameof(jsonApiRequest));
+            _resourceContextProvider = resourceContextProvider;
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/JsonApiReader.cs:37]: Missing null check

File: src/JsonApiDotNetCore/Serialization/JsonApiReader.cs [hunk 2]
```diff
@@ -134,5 +166,27 @@ private async Task<string> GetRequestBody(Stream body)
...
+            }
+
+            return model == null ? new Type[0] : new[] { model.GetType() };
+        }
+
+        private Type GetEndpointResourceType()
+        {
+            return _jsonApiRequest.Kind == EndpointKind.Primary
+                ? _jsonApiRequest.PrimaryResource.ResourceType 
+                : _jsonApiRequest.SecondaryResource?.ResourceType;
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/JsonApiReader.cs:189]: I'm not 100% sure if there are cases where this can fail, but I think using secondary with fallback to primary is more robust. So without checking `Kind` first. Because `Kind != Primary` does not always mean `Kind.Secondary`, it could mean `Kind.Relationship` too.

File: src/JsonApiDotNetCore/Serialization/JsonApiReader.cs [hunk 3]
```diff
@@ -16,17 +21,20 @@ namespace JsonApiDotNetCore.Serialization
...
-            IJsonApiRequest request,
+            IJsonApiRequest jsonApiRequest,
+            IResourceContextProvider resourceContextProvider,
             ILoggerFactory loggerFactory)
         {
             if (loggerFactory == null) throw new ArgumentNullException(nameof(loggerFactory));
 
             _deserializer = deserializer ?? throw new ArgumentNullException(nameof(deserializer));
-            _request = request ?? throw new ArgumentNullException(nameof(request));
+            _jsonApiRequest = jsonApiRequest ?? throw new ArgumentNullException(nameof(jsonApiRequest));
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/JsonApiReader.cs:36]: I did a solution-wide refactoring in #808 to rename all parameters and fields of type `IJsonApiRequest` from `jsonApiRequest` to `request` (and the same for options) and would like to keep it that way.

File: src/JsonApiDotNetCore/Serialization/JsonApiReader.cs [hunk 4]
```diff
@@ -63,22 +71,46 @@ public async Task<InputFormatterResult> ReadAsync(InputFormatterContext context)
...
+            ValidateIncomingResourceType(context, model);
+            
             return await InputFormatterResult.SuccessAsync(model);
         }
 
+        private void ValidateIncomingResourceType(InputFormatterContext context, object model)
+        {
+            if (context.HttpContext.IsJsonApiRequest() && IsPatchOrPostRequest(context.HttpContext.Request))
+            {
+                var endPointResourceType = GetEndpointResourceType();
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/JsonApiReader.cs:83]: `endPointResourceType` should have lowercase 'p' (same as in method name)

File: src/JsonApiDotNetCore/Serialization/JsonApiReader.cs [hunk 5]
```diff
@@ -63,22 +71,46 @@ public async Task<InputFormatterResult> ReadAsync(InputFormatterContext context)
...
+                var bodyResourceTypes = GetBodyResourceTypes(model);
+
+                foreach (var bodyResourceType in bodyResourceTypes)
+                {
+                    if (bodyResourceType != null && endPointResourceType != null && bodyResourceType != endPointResourceType)
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/JsonApiReader.cs:88]: I don't think `bodyResourceType` can ever be null, so comparing both without the null checks should be fine. If not, entering the loop only when `endPointResourceType != null` (check upfront) seems more appropriate, as the condition never changes when iterating through the loop.

**Review by bart-degreed — CHANGES_REQUESTED** [review]
Nice, Looks great!

File: src/JsonApiDotNetCore/Serialization/JsonApiReader.cs (hunk 1 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Serialization/JsonApiReader.cs:37]: Good catch, will add

File: src/JsonApiDotNetCore/Serialization/JsonApiReader.cs (hunk 3 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Serialization/JsonApiReader.cs:36]: Good catch, will modify

File: src/JsonApiDotNetCore/Serialization/JsonApiReader.cs (hunk 4 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Serialization/JsonApiReader.cs:83]: Good catch, will modify

File: src/JsonApiDotNetCore/Serialization/JsonApiReader.cs (hunk 5 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Serialization/JsonApiReader.cs:88]: Your right! the `bodyResourceType` null check is redundant because when the resource type from the body resolves to `null`, this is already caught [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/f27e020418c5f08762f57a85f221f3aa698019b8/src/JsonApiDotNetCore/Serialization/JsonApiReader.cs#L182).

Will process both suggestions

File: src/JsonApiDotNetCore/Serialization/JsonApiReader.cs (hunk 2 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Serialization/JsonApiReader.cs:189]: At this stage `Kind` can only be `Relationship` or `Primary, because there can be no json:api POST or PATCH request on a secondary endpoint. `POST /todoItems/1/assignee` is not supported

A fallback on the primary resource when the secondary resource is `null` will also not suffice, because it is possible to have a request on a `Kind.Relationship` endpoint with an unknown relationship, in which case the `null` is actually desired and should not lead to a fallback to the primary resource. See [Fails_On_Unknown_Relationship](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/f27e020418c5f08762f57a85f221f3aa698019b8/test/JsonApiDotNetCoreExampleTests/Acceptance/Spec/UpdatingRelationshipsTests.cs#L774).

Comment (bart-degreed) [reply src/JsonApiDotNetCore/Serialization/JsonApiReader.cs]: Good points! So this already was the best approach after all, let's leave it like that.

File: src/JsonApiDotNetCore/Serialization/JsonApiReader.cs [hunk 6]
```diff
@@ -134,5 +170,27 @@ private async Task<string> GetRequestBody(Stream body)
...
         }
+        
+        private bool IsPatchOrPostRequest(HttpRequest request)
+        {
+            return request.Method == HttpMethods.Patch || request.Method == HttpMethods.Post;
+        }
+
+        private IEnumerable<Type> GetBodyResourceTypes(object model)
+        {
+            if (model is ICollection<IIdentifiable> resourceCollection)
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/JsonApiReader.cs:181]: This can be `IEnumerable<T>` now.

**Review by bart-degreed — CHANGES_REQUESTED** [review]
Looking good, one more small change.

File: src/JsonApiDotNetCore/Serialization/JsonApiReader.cs (hunk 6 above)
Comment (maurei) [reply src/JsonApiDotNetCore/Serialization/JsonApiReader.cs]: Fixed!

**Review by bart-degreed — APPROVED** [review]
