### PR TITLE
JADNC: Required Input validation disabled for partial patching / relationships

### LINKED ISSUE #472: PATCH with ValidateModelState enabled and [Required] attribute
If I provide ValidateModelState =true, then every PATCH failed on validation 
on properties with [Required] attribute.
For example I have three properties with [Required], but sending patch to one of them only. Then
two of them failed on validation.

I found that AspNetCore uses JsonPatchDocument for this use case, but maybe I missed something.
Do you know how to deal with it? 

- JsonApiDotNetCore Version: 3.0.1-alpha4

### PR DESCRIPTION
**Pull request by sasman0001**
Fixes #472

This feature allows the Required validator to be disabled. This will allow partial patching in the case that the attribute is excluded from a patch. Validation is applied when the attribute is present in post or patch. 

Required validation also disabled for a relationships attributes (in attempt to fix [#472 (comment)](https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/472#issuecomment-462479751)).

### CODE REVIEW

**Comment by sasman0001** [comment]
FYI. Integration / unit tests succeed locally, but for some reason are failing according to the "AppVeyor build." Will investigate.

File: src/JsonApiDotNetCore/Serialization/Common/BaseDocumentParser.cs [hunk 1]
```diff
@@ -12,15 +12,19 @@
...
 namespace JsonApiDotNetCore.Serialization
 {
     /// <summary>
     /// Abstract base class for deserialization. Deserializes JSON content into <see cref="Document"/>s
     /// And constructs instances of the resource(s) in the document body.
     /// </summary>
-    public abstract class BaseDocumentParser
+    public abstract class BaseDocumentParser : IJsonApiDeserializer
     {
+        public InputFormatterContext Context { get; set; }
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/Common/BaseDocumentParser.cs:26]: I expect this needs to move up in the type hierarchy too. And I think it can be HttpContextAccessor instead, which is injectable. And then you can remove the `Context == null` checks.

File: src/JsonApiDotNetCore/Serialization/Common/BaseDocumentParser.cs [hunk 2]
```diff
@@ -46,7 +50,7 @@ protected BaseDocumentParser(IResourceContextProvider contextProvider, IResource
         protected abstract void AfterProcessField(IIdentifiable entity, IResourceField field, RelationshipEntry data = null);
 
         /// <inheritdoc/>
-        protected object Deserialize(string body)
+        public object Deserialize(string body)
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/Common/BaseDocumentParser.cs:53]: Why was this made public?

File: test/JsonApiDotNetCoreExampleTests/JsonApiDotNetCoreExampleTests.csproj [hunk 3]
```diff
@@ -16,6 +16,7 @@
   <ItemGroup>
     <PackageReference Include="Bogus" Version="$(BogusVersion)" />
     <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="$(AspNetCoreVersion)" />
+    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
```
Comment (bart-degreed) [inline test/JsonApiDotNetCoreExampleTests/JsonApiDotNetCoreExampleTests.csproj:19]: Why was this added?

File: src/JsonApiDotNetCore/Serialization/Common/BaseDocumentParser.cs [hunk 4]
```diff
@@ -101,14 +122,15 @@ protected IIdentifiable SetRelationships(IIdentifiable entity, Dictionary<string
             var entityProperties = entity.GetType().GetProperties();
             foreach (var attr in relationshipAttributes)
             {
+                DisableValidator(attr.PropertyInfo.Name, "Relation");
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/Common/BaseDocumentParser.cs:125]: Can you please explain how relationships (are supposed to) interact with this attribute?

File: src/JsonApiDotNetCore/Serialization/Common/BaseDocumentParser.cs [hunk 5]
```diff
@@ -71,21 +75,38 @@ protected object Deserialize(string body)
...
-                if (attributeValues.TryGetValue(attr.PublicAttributeName, out object newValue))
+                if (attributeValues == null || attributeValues.Count == 0)
                 {
-                    var convertedValue = ConvertAttrValue(newValue, attr.PropertyInfo.PropertyType);
-                    attr.SetValue(entity, convertedValue);
-                    AfterProcessField(entity, attr);
+                    if (Context == null || Context.HttpContext.Request.Method != "PATCH") continue;
+                    if (attr.PropertyInfo.GetCustomAttribute<Required>() != null)
+                    {
+                        DisableValidator(attr.PropertyInfo.ReflectedType?.Name, attr.PropertyInfo.Name);
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/Common/BaseDocumentParser.cs:85]: Can .ReflectedType really be null? And if so, you'd be passing `null` to the method, which looks wrong. And why use .ReflectedType instead of .PropertyType?

File: src/JsonApiDotNetCore/Serialization/Common/BaseDocumentParser.cs [hunk 6]
```diff
@@ -71,21 +75,38 @@ protected object Deserialize(string body)
         /// <returns></returns>
         protected IIdentifiable SetAttributes(IIdentifiable entity, Dictionary<string, object> attributeValues, List<AttrAttribute> attributes)
         {
-            if (attributeValues == null || attributeValues.Count == 0)
-                return entity;
-
             foreach (var attr in attributes)
             {
-                if (attributeValues.TryGetValue(attr.PublicAttributeName, out object newValue))
+                if (attributeValues == null || attributeValues.Count == 0)
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/Common/BaseDocumentParser.cs:80]: Passing `null` for collections is an anti-pattern, so I wouldn't check for that unless their parameter is declared as optional with null as default value (which is still odd).

File: src/JsonApiDotNetCore/Serialization/Common/BaseDocumentParser.cs [hunk 7]
```diff
@@ -71,21 +75,38 @@ protected object Deserialize(string body)
...
                 {
-                    var convertedValue = ConvertAttrValue(newValue, attr.PropertyInfo.PropertyType);
-                    attr.SetValue(entity, convertedValue);
-                    AfterProcessField(entity, attr);
+                    if (Context == null || Context.HttpContext.Request.Method != "PATCH") continue;
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/Common/BaseDocumentParser.cs:82]: I think you can use the pseudo-constant `HttpMethod.Patch` here.

File: src/JsonApiDotNetCore/Models/CustomValidators/RequiredIfEnabled.cs [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+        {
+            CheckDisableKey(validationContext);
+            return Disabled ? ValidationResult.Success : base.IsValid(value, validationContext);
+        }
+
+        private void CheckDisableKey(ValidationContext validationContext)
+        {
+            var httpContextAccessor = (IHttpContextAccessor)validationContext.GetRequiredService(typeof(IHttpContextAccessor));
+            Disabled = httpContextAccessor.HttpContext.Items.ContainsKey($"DisableValidation_{validationContext.ObjectType.Name}_{validationContext.MemberName}") 
+                       || httpContextAccessor.HttpContext.Items.ContainsKey($"DisableValidation_{validationContext.ObjectType.Name}_Relation");
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Models/CustomValidators/RequiredIfEnabled.cs:26]: Nit: I prefer the || at the end of the previous line.

File: src/Examples/ReportsExample/ReportsExample.csproj [hunk 9]
```diff
@@ -8,6 +8,7 @@
   </ItemGroup>
 
   <ItemGroup>
-    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="$(NpgsqlPostgreSQLVersion)" />
+    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.5" />
```
Comment (bart-degreed) [inline src/Examples/ReportsExample/ReportsExample.csproj:11]: We have wildcard-based placeholders in Directory.Build.Props for ASP.NET Core assembly versions, please use that instead. It enables library consumers to be at, for example, .NET Core 3.1.3 and still use JADNC.

File: test/JsonApiDotNetCoreExampleTests/Acceptance/ResourceDefinitions/ResourceDefinitionTests.cs [hunk 10]
```diff
@@ -609,5 +609,380 @@ public async Task Cascade_Permission_Error_Delete_ToMany_Relationship()
...
+            var body = await response.Content.ReadAsStringAsync();
+            var errorDocument = JsonConvert.DeserializeObject<ErrorDocument>(body);
+            Assert.Single(errorDocument.Errors);
+            Assert.Equal("Input validation failed.", errorDocument.Errors[0].Title);
+            Assert.Equal("422", errorDocument.Errors[0].Status);
+            Assert.Equal("The Name field is required.", errorDocument.Errors[0].Detail);
+        }
+
+        [Fact]
+        public async Task Update_Article_With_Required_AllowEmptyString_True_Name_Attribute_Empty_Succeeds()
```
Comment (bart-degreed) [inline test/JsonApiDotNetCoreExampleTests/Acceptance/ResourceDefinitions/ResourceDefinitionTests.cs:948]: All the other tests you added do not mention AllowEmptyString_True in their names, so I think it can be left out here too.

**Comment by bart-degreed** [comment]
The cibuild failure is likely unrelated to your work. Some tests are still not properly isolated, which makes them fail occasionally (tracked at #715). Usually pushing another empty commit makes the build succeed.

**Comment by bart-degreed** [comment]
Please merge the latest master into your branch and see if all still works before we take this PR.

File: src/JsonApiDotNetCore/Serialization/Server/RequestDeserializer.cs [hunk 11]
```diff
@@ -50,5 +57,42 @@ protected override void AfterProcessField(IIdentifiable entity, IResourceField f
...
+                }
+
+                if (!disableValidator) continue;
+                if (_httpContextAccessor.HttpContext.Request.Method != HttpMethod.Patch.Method) continue;
+                if (attr.PropertyInfo.GetCustomAttribute<IsRequiredAttribute>() != null)
+                    _httpContextAccessor.HttpContext.DisableValidator(attr.PropertyInfo.Name,
+                        entity.GetType().Name);
+            }
+
+            return base.SetAttributes(entity, attributeValues, attributes);
```
Comment (bart-degreed) [inline src/JsonApiDotNetCore/Serialization/Server/RequestDeserializer.cs:85]: I cleaned this up a bit:
- extract conditions out of the loop that do not vary based on loop variable
- replaced multiple ifs with a single expression

```c#
if (_httpContextAccessor.HttpContext.Request.Method == HttpMethod.Patch.Method)
{
    foreach (AttrAttribute attr in attributes)
    {
        if (attr.PropertyInfo.GetCustomAttribute<IsRequiredAttribute>() != null)
        {
            bool disableValidator = attributeValues == null || attributeValues.Count == 0 ||
                                    !attributeValues.TryGetValue(attr.PublicAttributeName, out _);

            if (disableValidator)
            {
                _httpContextAccessor.HttpContext.DisableValidator(attr.PropertyInfo.Name, entity.GetType().Name);
            }
        }
    }
}

return base.SetAttributes(entity, attributeValues, attributes);
```

File: test/JsonApiDotNetCoreExampleTests/Acceptance/ResourceDefinitions/ResourceDefinitionTests.cs [hunk 12]
```diff
@@ -609,5 +613,380 @@ public async Task Cascade_Permission_Error_Delete_ToMany_Relationship()
             Assert.Equal("You are not allowed to update fields or relationships of locked todo items.", errorDocument.Errors[0].Title);
             Assert.Null(errorDocument.Errors[0].Detail);
         }
+
+        [Fact]
+        public async Task Create_Article_With_IsRequired_Name_Attribute_Succeeds()
```
[the remark this answers is not in the document]
Comment (sasman0001) [reply test/JsonApiDotNetCoreExampleTests/Acceptance/ResourceDefinitions/ResourceDefinitionTests.cs:618]: Good idea. They are better placed here.

**Comment by sasman0001** [comment]
Bart, I pulled the latest master, but then thought since this is my fork, it may not actually be pulling the JADNC master. I am not familiar with "forking" and am unsure how to merge JADNC master into my fork. 

I have made the other changes you requested. Thank you for all the great feedback.

**Comment by bart-degreed** [comment]
git fetch upstream
git checkout yourbranch
git merge upstream/master

In the same way you can sync your forked master branch. Hope this helps.

**Comment by bart-degreed** [comment]
Thanks a lot, Sarah!
