### PR TITLE
Various fixes and improvements

### LINKED ISSUE #1110: Relationship update request may query read-only replica
This bug affects APIs that use a master database to write changes to while using a set of read-only replicates to serve GET requests.

The query to determine initial state is sent to the read-only database on POST Many-to-many and DELETE To-many relationship requests.

Affected code:
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/1b01e521652c59aaa1053ee28323a9f740a7b7d2/src/JsonApiDotNetCore/Services/JsonApiResourceService.cs#L350

Instead it should call:
```c#
_repositoryAccessor.GetForUpdateAsync()
```

### PR DESCRIPTION
**Pull request by bart-degreed**
Various fixes and improvements that I wrote down over the last few weeks while working on other things. See the individual commits for details.

Fixes #1110 and #1106.

#### QUALITY CHECKLIST
- [x] Changes implemented in code
- [x] Complies with our [contributing guidelines](./.github/CONTRIBUTING.md)
- [x] Adapted tests
- [x] Documentation updated
- [ ] N/A: Created issue to update [Templates](https://github.com/json-api-dotnet/Templates/issues/new): {ISSUE_NUMBER}

### CODE REVIEW

File: src/JsonApiDotNetCore/Serialization/Response/ResponseModelAdapter.cs [hunk 1]
```diff
@@ -211,12 +211,12 @@ protected virtual ResourceObject ConvertResource(IIdentifiable resource, Resourc
             return resourceObject;
         }
 
-        protected virtual IDictionary<string, object?>? ConvertAttributes(IIdentifiable resource, ResourceType resourceType,
+        protected virtual IDictionary<string, object?>? ConvertAttributes(IIdentifiable resource, ResourceType type,
```
Comment (maurei) [inline src/JsonApiDotNetCore/Serialization/Response/ResponseModelAdapter.cs:214]: The former was more consistent with the rest of the codebase. `ResourceType resourceType` has 151 matches, whereas `ResourceType type` had 3 prior to this change. More specifically, the combination `(IIdentifiable resource, ResourceType resourceType)` has 10 matches, whereas the `(IIdentifiable resource, ResourceType type)` has none.

Comment (bart-degreed) [reply src/JsonApiDotNetCore/Serialization/Response/ResponseModelAdapter.cs:214]: I did this to align with existing methods in this file:
- `private void TraverseResource(IIdentifiable resource, ResourceType type, EndpointKind kind, IImmutableSet<IncludeElementExpression> includeElements,
            ResourceObjectTreeNode parentTreeNode, RelationshipAttribute? parentRelationship)`
- `private ResourceObjectTreeNode GetOrCreateTreeNode(IIdentifiable resource, ResourceType type, EndpointKind kind)`
- `protected virtual ResourceObject ConvertResource(IIdentifiable resource, ResourceType type, EndpointKind kind)`

**Review by maurei — APPROVED** [review]
