### PR TITLE
Fixing issue where total-records was 0 on POST and PATCH calls.

### LINKED ISSUE #307: total-records on POST and PATCH methods
On POST and PATCH methods, I noticed that total-records is returned as 0. I think this should either be 1 or that meta attribute should not be included.

### PR DESCRIPTION
**Pull request by nwise**
Closes #307

#### BUG FIX
- [x] reproduce issue in tests
- [x] fix issue
- [ ] bump package version

### CODE REVIEW

File: src/JsonApiDotNetCore/Services/JsonApiContext.cs [hunk 1]
```diff
@@ -119,11 +119,13 @@ private PageManager GetPageManager()
                 return new PageManager();
 
             var query = QuerySet?.PageQuery ?? new PageQuery();
+            var requestMethod = _httpContextAccessor.HttpContext.Request.Method;
 
             return new PageManager
             {
                 DefaultPageSize = Options.DefaultPageSize,
                 CurrentPage = query.PageOffset,
+                TotalRecords = (requestMethod == "POST" || requestMethod == "PATCH") ? 1 : 0,
```
Comment (jaredcnance) [inline src/JsonApiDotNetCore/Services/JsonApiContext.cs]: I feel like this may change the semantics of TotalRecords a bit. Since in GET requests, TotalRecords indicates the number of records in the database and not the number of records in the response, this would change the meaning of the field for POST and PATCH requests.

**Comment by nwise** [comment]
Yeah, that makes sense. I'd prefer that, if the total-records value is included, it should be accurate. What do you think about simply not adding it on PATCH/POST responses? I think that would be simplest and also not require an extra call to the DB.

**Comment by jaredcnance** [comment]
Yeah I 100% agree. I think we should exclude it in those cases.

**Comment by milosloub** [comment]
I think that this is good idea. Property TotalRecords corresponds to amount of returned data in case of filtering. So in case of POST and PATCH is good idea to set TotalRecords  : 1. It trully returns only one record.

**Comment by milosloub** [comment]
I'm sorry. I didn't notice 

> Yeah I 100% agree. I think we should exclude it in those cases.

I think this is better solution to exlude in all irrelevant cases. My suggestion was for "total-record" always presented

**Comment by jaredcnance** [comment]
I _think_ we can simply make `TotalRecords` `int?` and change the following line from:
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/8f7f0f7e2112993d656258b779afd784ac5b1b99/src/JsonApiDotNetCore/Builders/DocumentBuilder.cs#L78-L79

to:
 
```c#
if (_jsonApiContext.Options.IncludeTotalRecordCount && _jsonApiContext.PageManager.TotalRecords != null) 
  builder.Add( /* ... */ )
```

What this implies is that it will only be included if we have explicitly set it earlier in the pipeline.

**Comment by jaredcnance** [comment]
Hey guys, take a look at the changes and let me know what you think. I've modified it so even if the payload returns empty, we will still include the `total-records` meta attribute. Example:

```http
GET /api/articles HTTP/1.1
Accept: application/vnd.api+json
```
```http
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{ "data": [], "meta": { "total-records":0 } }
```

**Comment by nwise** [comment]
I think this looks good. I like that it's always included on empty results too. It will make coding clients against it simpler. Thanks!
