### PR TITLE
Fix missing HttpContext on ValidationContext during atomic operations

### LINKED ISSUE #1250: `ValidationContext` does not have a `ServiceProvider` on atomic operations
#### DESCRIPTION

This bug assumes I have a model implementing `IValidatableObject` and injecting a service for the validation. A use-case for this is injecting `ITargetedFields` to check if a field needs to be validated or not on a `PATCH` request (#1204).

If I try to create or update this model through an atomic operations, then I cannot inject any service because `ServiceProvider` is `null`.

#### STEPS TO REPRODUCE

Create the following object

```csharp
[UsedImplicitly(ImplicitUseTargetFlags.Members)]
[Resource]
public sealed class Person : Identifiable<int>, IValidatableObject
{
    [Attr]
    public string Name { get; set; } = null!;

    [HasMany]
    public ICollection<Book> Books { get; set; } = new List<Book>();

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        IJsonApiRequest service = validationContext.GetRequiredService<IJsonApiRequest>();

        // do something with the service

        return Enumerable.Empty<ValidationResult>();
    }
}
```

Try to update it with an atomic operation
```json
{
  "atomic:operations": [
    {
      "op": "add",
      "data": {
        "type": "people",
        "attributes": {
          "name": ""
        }
      }
    }
  ]
}
```

#### EXPECTED BEHAVIOR

The object is created.

#### ACTUAL BEHAVIOR

The creation fails with the following error

```json
{
    "links": {
        "self": "/api/operations"
    },
    "errors": [
        {
            "id": "af29550f-225c-4386-87b9-523633e3db3e",
            "status": "500",
            "title": "An unhandled error occurred while processing this request.",
            "detail": "No service for type 'JsonApiDotNetCore.Middleware.IJsonApiRequest' has been registered."
        }
    ]
}
```

#### VERSIONS USED
- JsonApiDotNetCore version: 5.1.1
- ASP.NET Core version: .NET 7
- Entity Framework Core version: EFCore 6
- Database provider: SQL Server

### PR DESCRIPTION
**Pull request by Tommy228**
Closes #1250

This PR
* Adds `HttpContext` to the `ValidationContext` when validating objects during atomic operations, allowing dependency injection
* Adds a test case to the integration tests to validate this

#### QUALITY CHECKLIST
- [x] Changes implemented in code
- [x] Complies with our [contributing guidelines](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/.github/CONTRIBUTING.md)
- [x] Adapted tests
- [ ] N/A Documentation updated

### CODE REVIEW

**Comment by bkoelman** [comment]
Hi @Tommy228, thanks for your contribution! I intend to look at it somewhere this week.

File: test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/ModelStateValidation/AtomicModelStateValidationTests.cs [hunk 1]
```diff
@@ -67,6 +73,48 @@ public async Task Cannot_create_resource_with_multiple_violations()
...
+        // Assert
+        httpResponse.ShouldHaveStatusCode(HttpStatusCode.UnprocessableEntity);
+
+        responseDocument.Errors.ShouldHaveCount(1);
+
+        ErrorObject error = responseDocument.Errors[0];
+        error.StatusCode.Should().Be(HttpStatusCode.UnprocessableEntity);
+        error.Title.Should().Be("Input validation failed.");
+        error.Detail.Should().Be("Release date must be in the past.");
+        error.Source.Should().BeNull();
```
Comment (bkoelman) [inline test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/ModelStateValidation/AtomicModelStateValidationTests.cs:115]: The source pointer isn't populated because the custom validator acts on the `MusicTrack` class, instead of the `ReleasedAt` property.

By using the approach below, the source pointer does get populated (and the validation becomes reusable):
```c#
public sealed class MusicTrack : Identifiable<Guid>
{
    [Attr]
    [DateMustBeInThePast]
    public DateTimeOffset ReleasedAt { get; set; }
}

[AttributeUsage(AttributeTargets.Property)]
internal sealed class DateMustBeInThePastAttribute : ValidationAttribute
{
    protected override ValidationResult? IsValid(object? value, ValidationContext validationContext)
    {
        var targetedFields = validationContext.GetRequiredService<ITargetedFields>();

        if (targetedFields.Attributes.Any(attribute => attribute.Property.Name == validationContext.MemberName))
        {
            PropertyInfo propertyInfo = validationContext.ObjectType.GetProperty(validationContext.MemberName!)!;

            if (propertyInfo.PropertyType == typeof(DateTimeOffset) || propertyInfo.PropertyType == typeof(DateTimeOffset?))
            {
                var typedValue = (DateTimeOffset?)propertyInfo.GetValue(validationContext.ObjectInstance);
                var systemClock = validationContext.GetRequiredService<ISystemClock>();

                if (typedValue >= systemClock.UtcNow)
                {
                    return new ValidationResult($"{validationContext.MemberName} must be in the past.");
                }
            }
        }

        return ValidationResult.Success;
    }
}
```
Which results in:
```json
"status": "422",
"title": "Input validation failed.",
"detail": "ReleasedAt must be in the past.",
"source": {
  "pointer": "/atomic:operations[0]/data/attributes/releasedAt"
}
```

File: test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/ModelStateValidation/AtomicModelStateValidationTests.cs [hunk 2]
```diff
@@ -16,6 +19,9 @@ public AtomicModelStateValidationTests(IntegrationTestContext<TestableStartup<Op
     {
         _testContext = testContext;
 
+        _testContext.ConfigureServicesBeforeStartup(services =>
+            services.AddSingleton<IReleasedAtValidator, ReleasedAtValidator>().AddSingleton<ISystemClock, SystemClock>());
```
Comment (bkoelman) [inline test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/ModelStateValidation/AtomicModelStateValidationTests.cs:23]: Assuming this is going to stay, please put the two registrations in individual statements. It makes it easier to spot the dependencies.

File: test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/Validation/ReleasedAtValidator.cs [hunk 3]
```diff
@@ -0,0 +1,19 @@
+﻿using System.ComponentModel.DataAnnotations;
+using Microsoft.AspNetCore.Authentication;
+
+namespace JsonApiDotNetCoreTests.IntegrationTests.AtomicOperations.Validation;
+
+public sealed class ReleasedAtValidator : IReleasedAtValidator
```
Comment (bkoelman) [inline test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/Validation/ReleasedAtValidator.cs:6]: Assuming these types are going to stay, please move them up one directory. We try to use the subdirectories for the tests and put shared files above them.

**Review by bkoelman — COMMENTED** [review]
Thanks for carefully adhering to our code style and naming conventions. See comments below.

File: test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/ModelStateValidation/AtomicModelStateValidationTests.cs (hunk 1 above)
Comment (Tommy228) [reply test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/ModelStateValidation/AtomicModelStateValidationTests.cs:115]: You're right, that's a much better approach! And it will still test that the dependency injection is working properly. I'll update the PR according to this.

**Review by bkoelman — CHANGES_REQUESTED** [review]

File: test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/Creating/AtomicCreateResourceTests.cs [hunk 4]
```diff
@@ -26,6 +27,11 @@ public AtomicCreateResourceTests(IntegrationTestContext<TestableStartup<Operatio
         testContext.UseController<MusicTracksController>();
         testContext.UseController<PlaylistsController>();
 
+        testContext.ConfigureServicesBeforeStartup(services =>
+        {
+            services.AddSingleton<ISystemClock, SystemClock>();
```
[the remark this answers is not in the document]
Comment (Tommy228) [reply test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations/Creating/AtomicCreateResourceTests.cs:32]: No worries. This is what I would usually do with `FakeClock` using `NodaTime`. I didn’t bother with it for this test but it’s definitely the good practice. I’ll update the PR later this day .

**Review by bkoelman — APPROVED** [review]
