### PR TITLE
Resource-specific meta

### LINKED ISSUE #737: IHasMeta does not work
Example:

```csharp
    public class Person : Identifiable, IHasMeta
    {
        [Attr]
        public string FirstName { get; set; }
        
        [Attr]
        public string LastName { get; set; }

        public Dictionary<string, object> GetMeta()
        {
            return new Dictionary<string, object>
            {
                {"copyright", "Copyright 2018 Example Corp."},
                {"authors", new[] {"John Doe"}}
            };
        }
    }
```

```
curl https://localhost:44354/people
```

```json
{"links":{"self":"https://localhost:44354///people"},"data":[{"type":"people","id":"1","attributes":{"firstName":"John","lastName":"Simmons"},"links":{"self":"https://localhost:44354///people/1"}},{"type":"people","id":"2","attributes":{"firstName":"Pete","lastName":"Bell"},"links":{"self":"https://localhost:44354///people/2"}}]}
```

### PR DESCRIPTION
**Pull request by bart-degreed**
Fixes #737.

### CODE REVIEW

File: src/JsonApiDotNetCore/Serialization/Building/IResourceObjectBuilder.cs [hunk 1]
```diff
@@ -16,9 +16,10 @@ public interface IResourceObjectBuilder
         /// Adds the attributes and relationships that are enlisted in <paramref name="attributes"/> and <paramref name="relationships"/>.
         /// </summary>
         /// <param name="resource">Resource to build a <see cref="ResourceObject"/> for.</param>
+        /// <param name="includeResourceMeta">When <c>true</c>, retrieves resource-specific meta from <see cref="IResourceDefinition{TResource}"/>.</param>
         /// <param name="attributes">Attributes to include in the building process.</param>
         /// <param name="relationships">Relationships to include in the building process.</param>
         /// <returns>The resource object that was built.</returns>
-        ResourceObject Build(IIdentifiable resource, IReadOnlyCollection<AttrAttribute> attributes, IReadOnlyCollection<RelationshipAttribute> relationships);
+        ResourceObject Build(IIdentifiable resource, bool includeResourceMeta, IReadOnlyCollection<AttrAttribute> attributes, IReadOnlyCollection<RelationshipAttribute> relationships);
```
Comment (maurei) [inline src/JsonApiDotNetCore/Serialization/Building/IResourceObjectBuilder.cs:23]: I think it would be favorable to implement resource-level metadata without having it ripple through to the public API of `ResourceObjectBuilder`. The metadata can be assigned in the `ResponseSerializer` class

**Review by maurei — APPROVED** [review]

File: src/JsonApiDotNetCore/Serialization/Building/IResourceObjectBuilder.cs (hunk 1 above)
Comment (bart-degreed) [reply src/JsonApiDotNetCore/Serialization/Building/IResourceObjectBuilder.cs]: This is not possible, because `ResourceDefinition.GetMeta` requires a resource instance, not a `ResourceObject`. After offline discussion, we found that the best solution is to replace the boolean flag with an overridden Build method in `ResourceObjectBuilder`.

Comment (maurei) [reply src/JsonApiDotNetCore/Serialization/Building/IResourceObjectBuilder.cs]: We discussed this in a meeting and found a way around it.

**Review by maurei — APPROVED** [review]

**Comment by maurei** [comment]
👍
